from database.shard_router import (
    get_shard_primary_connection,
    get_shard_replica_connection,
    get_shard_id,
)


SHARDS = [1, 2]


# ============================================================
# CREATE USER
#
# WRITE → SELECTED SHARD PRIMARY
#
# ID is generated by PostgreSQL sequence.
#
# Shard 1 sequence → 1,3,5,7...
# Shard 2 sequence → 2,4,6,8...
#
# Therefore ID is globally unique.
# ============================================================

def create_user(shard_id, name, email):

    connection = get_shard_primary_connection(shard_id)

    try:

        with connection.cursor() as cursor:

            cursor.execute(
                """
                INSERT INTO users (name, email)
                VALUES (%s, %s)
                RETURNING id, name, email;
                """,
                (name, email),
            )

            user = cursor.fetchone()

            connection.commit()

            return user

    finally:

        connection.close()


# ============================================================
# GET ALL USERS FROM SPECIFIC SHARD
#
# READ → SPECIFIC SHARD REPLICA
# ============================================================

def get_users_from_shard(shard_id):

    connection = get_shard_replica_connection(shard_id)

    try:

        with connection.cursor() as cursor:

            cursor.execute(
                """
                SELECT id, name, email
                FROM users
                ORDER BY id;
                """
            )

            return cursor.fetchall()

    finally:

        connection.close()


# ============================================================
# GET ALL USERS
#
# READ → ALL SHARD REPLICAS
# ============================================================

def get_users():

    all_users = []

    for shard_id in SHARDS:

        users = get_users_from_shard(shard_id)

        for user in users:

            all_users.append(
                (
                    user[0],
                    user[1],
                    user[2],
                    shard_id,
                )
            )

    return sorted(
        all_users,
        key=lambda user: user[0]
    )


# ============================================================
# GET USER FROM SPECIFIC SHARD
#
# READ → SPECIFIC SHARD REPLICA
# ============================================================

def get_user_from_shard(shard_id, user_id):

    connection = get_shard_replica_connection(shard_id)

    try:

        with connection.cursor() as cursor:

            cursor.execute(
                """
                SELECT id, name, email
                FROM users
                WHERE id = %s;
                """,
                (user_id,),
            )

            return cursor.fetchone()

    finally:

        connection.close()


# ============================================================
# GET USER BY GLOBAL ID
#
# ID → SHARD ROUTER
# READ → CORRECT SHARD REPLICA
#
# Example:
#
# ID 7 → Shard 1 → Replica 5434
# ID 8 → Shard 2 → Replica 5436
# ============================================================

def get_user_by_id(user_id):

    shard_id = get_shard_id(user_id)

    user = get_user_from_shard(
        shard_id,
        user_id
    )

    return user, shard_id


# ============================================================
# SEARCH USERS
#
# READ → ALL SHARD REPLICAS
# ============================================================

def search_users(search_term):

    all_users = []

    for shard_id in SHARDS:

        connection = get_shard_replica_connection(shard_id)

        try:

            with connection.cursor() as cursor:

                cursor.execute(
                    """
                    SELECT id, name, email
                    FROM users
                    WHERE name ILIKE %s
                       OR email ILIKE %s
                    ORDER BY id;
                    """,
                    (
                        f"%{search_term}%",
                        f"%{search_term}%",
                    ),
                )

                users = cursor.fetchall()

                for user in users:

                    all_users.append(
                        (
                            user[0],
                            user[1],
                            user[2],
                            shard_id,
                        )
                    )

        finally:

            connection.close()

    return sorted(
        all_users,
        key=lambda user: user[0]
    )


# ============================================================
# COUNT USERS
#
# READ → ALL SHARD REPLICAS
# ============================================================

def count_users():

    total = 0

    for shard_id in SHARDS:

        connection = get_shard_replica_connection(shard_id)

        try:

            with connection.cursor() as cursor:

                cursor.execute(
                    """
                    SELECT COUNT(*)
                    FROM users;
                    """
                )

                total += cursor.fetchone()[0]

        finally:

            connection.close()

    return total


# ============================================================
# FIND USER IN SPECIFIC SHARD
# ============================================================

def find_user_in_shard(shard_id, user_id):

    return get_user_from_shard(
        shard_id,
        user_id
    )


# ============================================================
# UPDATE USER
#
# WRITE → SPECIFIC SHARD PRIMARY
# ============================================================

def update_user(shard_id, user_id, name):

    connection = get_shard_primary_connection(shard_id)

    try:

        with connection.cursor() as cursor:

            cursor.execute(
                """
                UPDATE users
                SET name = %s
                WHERE id = %s
                RETURNING id, name, email;
                """,
                (name, user_id),
            )

            updated_user = cursor.fetchone()

            connection.commit()

            return updated_user

    finally:

        connection.close()


# ============================================================
# UPDATE USER BY GLOBAL ID
#
# ID → SHARD ROUTER
# WRITE → CORRECT SHARD PRIMARY
# ============================================================

def update_user_by_id(user_id, name):

    shard_id = get_shard_id(user_id)

    user = update_user(
        shard_id,
        user_id,
        name
    )

    return user, shard_id


# ============================================================
# DELETE USER
#
# WRITE → SPECIFIC SHARD PRIMARY
# ============================================================

def delete_user(shard_id, user_id):

    connection = get_shard_primary_connection(shard_id)

    try:

        with connection.cursor() as cursor:

            cursor.execute(
                """
                DELETE FROM users
                WHERE id = %s
                RETURNING id, name, email;
                """,
                (user_id,),
            )

            deleted_user = cursor.fetchone()

            connection.commit()

            return deleted_user

    finally:

        connection.close()


# ============================================================
# DELETE USER BY GLOBAL ID
#
# ID → SHARD ROUTER
# WRITE → CORRECT SHARD PRIMARY
# ============================================================

def delete_user_by_id(user_id):

    shard_id = get_shard_id(user_id)

    user = delete_user(
        shard_id,
        user_id
    )

    return user, shard_id


# ============================================================
# SHARD 1 - CREATE USER
# ============================================================

def create_user_shard1(name, email):

    return create_user(
        1,
        name,
        email
    )


# ============================================================
# SHARD 1 - GET USER
# ============================================================

def get_user_shard1(user_id):

    return get_user_from_shard(
        1,
        user_id
    )


# ============================================================
# SHARD 2 - CREATE USER
# ============================================================

def create_user_shard2(name, email):

    return create_user(
        2,
        name,
        email
    )


# ============================================================
# SHARD 2 - GET USER
# ============================================================

def get_user_shard2(user_id):

    return get_user_from_shard(
        2,
        user_id
    )